## Importing Libraries

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Reading data 

In [50]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [51]:
df = pd.concat([train,test])

## Pre-processing data

In [12]:
df.isnull().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                            0
Age                             0
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary           0
Num_Bank_Accounts               0
Num_Credit_Card                 0
Interest_Rate                   0
Num_of_Loan                     0
Type_of_Loan                    0
Delay_from_due_date             0
Num_of_Delayed_Payment          0
Changed_Credit_Limit            0
Num_Credit_Inquiries            0
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age              0
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly         0
Payment_Behaviour               0
Monthly_Balance                 0
Credit_Score                50000
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df.shape

(100000, 28)

In [15]:
df.describe()

ID    Customer_ID          Month            Age  \
count  100000.000000  100000.000000  100000.000000  100000.000000   
mean    80631.500000   25982.666640       4.500000      33.316340   
std     43301.486619   14340.543051       2.291299      10.764812   
min      5634.000000    1006.000000       1.000000      14.000000   
25%     43132.750000   13664.500000       2.750000      24.000000   
50%     80631.500000   25777.000000       4.500000      33.000000   
75%    118130.250000   38385.000000       6.250000      42.000000   
max    155629.000000   50999.000000       8.000000      56.000000   

                SSN  Annual_Income  Monthly_Inhand_Salary  Num_Bank_Accounts  \
count  1.000000e+05  100000.000000          100000.000000      100000.000000   
mean   5.004617e+08   50505.123449            4197.270835           5.368820   
std    2.908267e+08   38299.422093            3186.432497           2.593314   
min    8.134900e+04    7005.930000             303.645417           0.000000   
25%    2.451686e+08   19342.972500            1626.594167           3.000000   
50%    5.006886e+08   36999.705000            3095.905000           5.000000   
75%    7.560027e+08   71683.470000            5957.715000           7.000000   
max    9.999934e+08  179987.280000           15204.633333          11.000000   

       Num_Credit_Card  Interest_Rate  ...  Delay_from_due_date  \
count    100000.000000   100000.00000  ...         100000.00000   
mean          5.533570       14.53208  ...             21.08141   
std           2.067098        8.74133  ...             14.80456   
min           0.000000        1.00000  ...              0.00000   
25%           4.000000        7.00000  ...             10.00000   
50%           5.000000       13.00000  ...             18.00000   
75%           7.000000       20.00000  ...             28.00000   
max          11.000000       34.00000  ...             62.00000   

       Num_of_Delayed_Payment  Changed_Credit_Limit  Num_Credit_Inquiries  \
count           100000.000000         100000.000000         100000.000000   
mean                13.313120             10.470323              5.798250   
std                  6.237166              6.609481              3.867826   
min                  0.000000              0.500000              0.000000   
25%                  9.000000              5.380000              3.000000   
50%                 14.000000              9.400000              5.000000   
75%                 18.000000             14.850000              8.000000   
max                 25.000000             29.980000             17.000000   

       Outstanding_Debt  Credit_Utilization_Ratio  Credit_History_Age  \
count     100000.000000             100000.000000       100000.000000   
mean        1426.220376                 32.285173          221.220460   
std         1155.129026                  5.116875           99.680716   
min            0.230000                 20.000000            1.000000   
25%          566.072500                 28.052567          144.000000   
50%         1166.155000                 32.305784          219.000000   
75%         1945.962500                 36.496663          302.000000   
max         4998.070000                 50.000000          404.000000   

       Total_EMI_per_month  Amount_invested_monthly  Monthly_Balance  
count        100000.000000            100000.000000    100000.000000  
mean            107.699208                55.101315       392.697586  
std             132.267056                39.006932       201.652719  
min               0.000000                 0.000000         0.007760  
25%              29.268886                27.959111       267.615983  
50%              66.462304                45.156550       333.865366  
75%             147.392573                71.295797       463.215683  
max            1779.103254               434.191089      1183.930696  

[8 rows x 21 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype  
---  ------                    --------------   -----  
 0   ID                        100000 non-null  int64  
 1   Customer_ID               100000 non-null  int64  
 2   Month                     100000 non-null  int64  
 3   Name                      100000 non-null  object 
 4   Age                       100000 non-null  float64
 5   SSN                       100000 non-null  float64
 6   Occupation                100000 non-null  object 
 7   Annual_Income             100000 non-null  float64
 8   Monthly_Inhand_Salary     100000 non-null  float64
 9   Num_Bank_Accounts         100000 non-null  float64
 10  Num_Credit_Card           100000 non-null  float64
 11  Interest_Rate             100000 non-null  float64
 12  Num_of_Loan               100000 non-null  float64
 13  Type_of_Loan              100000 non-null  ob

#### Ordinal Encoding

In [17]:
df['Occupation'].unique()

array(['Scientist', 'Teacher', 'Engineer', 'Entrepreneur', 'Developer',
       'Lawyer', 'Media_Manager', 'Doctor', 'Journalist', 'Manager',
       'Accountant', 'Musician', 'Mechanic', 'Writer', 'Architect'],
      dtype=object)

In [18]:
df['Credit_Mix'].unique()

array(['Good', 'Standard', 'Bad'], dtype=object)

In [19]:
df['Payment_Behaviour'].unique()

array(['High_spent_Small_value_payments',
       'Low_spent_Large_value_payments',
       'Low_spent_Medium_value_payments',
       'Low_spent_Small_value_payments',
       'High_spent_Medium_value_payments',
       'High_spent_Large_value_payments'], dtype=object)

In [20]:
df['Payment_of_Min_Amount'].unique()

array(['No', 'NM', 'Yes'], dtype=object)

In [21]:
df['Credit_Score'].unique()

array(['Good', 'Standard', 'Poor'], dtype=object)

In [22]:
credit_score = ['Poor','Standard','Good']
credit_mix = ['Bad','Standard','Good']
payment_behaviour = ['High_spent_Small_value_payments',
                     'Low_spent_Large_value_payments',
                     'Low_spent_Medium_value_payments',
                     'Low_spent_Small_value_payments',
                     'High_spent_Medium_value_payments',
                     'High_spent_Large_value_payments']
payment_of_min_amount = ['No', 'NM', 'Yes']
occupation = ['Scientist', 'Teacher', 'Engineer', 'Entrepreneur', 'Developer',
              'Lawyer', 'Media_Manager', 'Doctor', 'Journalist', 'Manager',
              'Accountant', 'Musician', 'Mechanic', 'Writer', 'Architect']
#loan_type = ['Auto Loan',' Credit-Builder Loan',' Personal Loan',
#             '  Home Equity Loan','Not Specified','No Data','  Mortgage Loan',
#             '  Student Loan',' Debt Consolidation Loan','Payday Loan']

In [23]:
ordinal_attributes = df[['Credit_Score','Credit_Mix','Payment_Behaviour','Payment_of_Min_Amount','Occupation']]

def ordinal_encoding(attr, order):
    ordinal_attributes[attr] = ordinal_attributes[attr].astype('category')
    ordinal_attributes[attr] = ordinal_attributes[attr].cat.reorder_categories(
        new_categories=order,
        ordered=True
    )

    return pd.Series(ordinal_attributes[attr].cat.codes, name=attr)

In [24]:
df['Credit_Score'] = ordinal_encoding('Credit_Score', credit_score)
credit_mix = ordinal_encoding('Credit_Mix', credit_mix)
payment_behaviour = ordinal_encoding('Payment_Behaviour', payment_behaviour)
payment_of_min_amount = ordinal_encoding('Payment_of_Min_Amount', payment_of_min_amount)
occupation = ordinal_encoding('Occupation', occupation)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documen

In [25]:
df_encoded = pd.concat([credit_mix,
                        payment_behaviour,
                        payment_of_min_amount,
                        occupation,
                        df['Credit_Score']],
                        axis=1
                        )

In [26]:
df_encoded.corr()

Credit_Mix  Payment_Behaviour  Payment_of_Min_Amount  \
Credit_Mix               1.000000           0.046118              -0.720420   
Payment_Behaviour        0.046118           1.000000              -0.038640   
Payment_of_Min_Amount   -0.720420          -0.038640               1.000000   
Occupation               0.000529           0.004228              -0.001774   
Credit_Score             0.498673           0.038381              -0.414525   

                       Occupation  Credit_Score  
Credit_Mix               0.000529      0.498673  
Payment_Behaviour        0.004228      0.038381  
Payment_of_Min_Amount   -0.001774     -0.414525  
Occupation               1.000000      0.000136  
Credit_Score             0.000136      1.000000

In [27]:
df_encoded.shape

(100000, 5)

In [40]:
X = df_encoded.drop(['Credit_Score'],axis=1)
y = df_encoded['Credit_Score']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [29]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
abc = AdaBoostClassifier(base_estimator=RandomForestClassifier())

#int(x) for x in np.linspace(start = 10, stop = 50, num = 10)
#parameters = {'base_estimator__min_samples_leaf':[5,7],
#              'n_estimators':[10,15],
#              'learning_rate':[1.0]}

#clf = GridSearchCV(abc, parameters,cv=10,scoring='f1',n_jobs=4)
abc.fit(X_train,y_train)

AdaBoostClassifier(base_estimator=RandomForestClassifier())

In [43]:
from xgboost import XGBClassifier
xgb = XGBClassifier(booster='gbtree')

xgb = XGBClassifier()
xgb.fit(X_train,y_train)


XGBClassifier(objective='multi:softprob')

In [44]:
y_pred = xgb.predict(X_test)
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[2921 2006  947]
 [1866 6633 2100]
 [  69  531 2927]]
0.62405
              precision    recall  f1-score   support

           0       0.60      0.50      0.54      5874
           1       0.72      0.63      0.67     10599
           2       0.49      0.83      0.62      3527

    accuracy                           0.62     20000
   macro avg       0.60      0.65      0.61     20000
weighted avg       0.65      0.62      0.62     20000



In [46]:
import pickle
pickle.dump(xgb, open('xgb.pkl','wb'))